/**
 * @author masterlinnn
 * @project Sudoku Solver
 */
package pkg2021;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;


public class Help extends javax.swing.JFrame {//Welcome Class

 
    public Help() {
        super("Sudoku Solver @Help");
        initComponents();
        
        String helpText = "";
        try {
            Scanner scFile = new Scanner(new File("SudokuHelp.txt"));
            while (scFile.hasNext()) {
            helpText += scFile.nextLine()+ "\n";
            }
            scFile.close();
        } catch (FileNotFoundException ex) {
            System.out.println("File Not Found! "+ ex.getMessage());
        }
        
        txaHelpText.setText(helpText);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        scpHelpText = new javax.swing.JScrollPane();
        txaHelpText = new javax.swing.JTextArea();
        btnClose = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Rage Italic", 1, 68)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Sudoku Solver");
        lblTitle.setToolTipText("");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 800, 70));

        lblTitle1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Help");
        getContentPane().add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 800, 70));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Icon.png"))); // NOI18N
        getContentPane().add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 160, 130));

        txaHelpText.setEditable(false);
        txaHelpText.setColumns(20);
        txaHelpText.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txaHelpText.setRows(5);
        txaHelpText.setOpaque(false);
        scpHelpText.setViewportView(txaHelpText);

        getContentPane().add(scpHelpText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 680, 340));

        btnClose.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnClose.setText("Close");
        btnClose.setContentAreaFilled(false);
        btnClose.setOpaque(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 300, 50));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Background1.jpg"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JScrollPane scpHelpText;
    private javax.swing.JTextArea txaHelpText;
    // End of variables declaration//GEN-END:variables
}//Welcome Class
