/**
 * @author masterlinnn
 * @project Sudoku Solver
 */
package pkg2021;


public class Menu extends javax.swing.JFrame {//Menu Class
    public Menu() {//Menu Class Constructor
        super("Sudoku Solver @Menu");
        initComponents();
    }//Menu Class Constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        lblLoginBtn = new javax.swing.JLabel();
        lblCreateUserBtn = new javax.swing.JLabel();
        lblForgotBtn = new javax.swing.JLabel();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Rage Italic", 1, 68)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Sudoku Solver");
        lblTitle.setToolTipText("");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 800, 70));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Icon.png"))); // NOI18N
        getContentPane().add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 160, 130));

        lblTitle2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("Menu");
        getContentPane().add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 800, 70));

        lblLoginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonImages/Login1.png"))); // NOI18N
        lblLoginBtn.setToolTipText("Login To An Account");
        lblLoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLoginBtnMouseExited(evt);
            }
        });
        getContentPane().add(lblLoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 300, 80));

        lblCreateUserBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonImages/Createuser1.png"))); // NOI18N
        lblCreateUserBtn.setToolTipText("Create New User");
        lblCreateUserBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateUserBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCreateUserBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCreateUserBtnMouseExited(evt);
            }
        });
        getContentPane().add(lblCreateUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 320, 80));

        lblForgotBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonImages/Forgot1.png"))); // NOI18N
        lblForgotBtn.setToolTipText("Find Username or Password");
        lblForgotBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgotBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblForgotBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblForgotBtnMouseExited(evt);
            }
        });
        getContentPane().add(lblForgotBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, 80));

        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Background2.jpg"))); // NOI18N
        getContentPane().add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblLoginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginBtnMouseEntered
        lblLoginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonImages/Login2.png")));
    }//GEN-LAST:event_lblLoginBtnMouseEntered

    private void lblLoginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginBtnMouseExited
        lblLoginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonImages/Login1.png")));
    }//GEN-LAST:event_lblLoginBtnMouseExited

    private void lblLoginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginBtnMouseClicked
        this.dispose();
        new Login(false).setVisible(true);
    }//GEN-LAST:event_lblLoginBtnMouseClicked

    private void lblCreateUserBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateUserBtnMouseClicked
        this.dispose();
        new CreateUser().setVisible(true);
    }//GEN-LAST:event_lblCreateUserBtnMouseClicked

    private void lblCreateUserBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateUserBtnMouseEntered
        lblCreateUserBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonImages/Createuser2.png")));
       // lblCreateUserBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonImages/forgot2.png")));
    }//GEN-LAST:event_lblCreateUserBtnMouseEntered

    private void lblCreateUserBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateUserBtnMouseExited
        lblCreateUserBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonImages/Createuser1.png")));
    }//GEN-LAST:event_lblCreateUserBtnMouseExited

    private void lblForgotBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotBtnMouseClicked
        this.dispose();
        new Forgot().setVisible(true);
    }//GEN-LAST:event_lblForgotBtnMouseClicked

    private void lblForgotBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotBtnMouseEntered
        lblForgotBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonImages/Forgot2.png")));
    }//GEN-LAST:event_lblForgotBtnMouseEntered

    private void lblForgotBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotBtnMouseExited
        lblForgotBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ButtonImages/Forgot1.png")));
    }//GEN-LAST:event_lblForgotBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblCreateUserBtn;
    private javax.swing.JLabel lblForgotBtn;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblLoginBtn;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle2;
    // End of variables declaration//GEN-END:variables
}//Menu Class Constructor
