/**
 * @author masterlinnn
 * @project Sudoku Solver
 */
package pkg2021;

/*====================Imports=====================*/
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.Timer;

/*====================Imports=====================*/

public class Welcome extends javax.swing.JFrame {//Welcome Class

    //Initialize timer
    private Timer timer;
    //Initialize time to countdown  1000ms = 1s Delay in milliseconds
    private int closeWindowDelay = 5000;

    public Welcome() {//Welcome Class Constructor
        super("Sudoku Solver @Welcome");
        initComponents();

        timer = new Timer(closeWindowDelay, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                closeWindow();
            }
        });
        timer.start();
        
    }//Welcome Class Constructor

    private void closeWindow() {
        timer.stop();
        this.dispose();
        new Menu().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Rage Italic", 1, 68)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Sudoku Solver");
        lblTitle.setToolTipText("");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 800, 70));

        lblTitle1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Welcome");
        getContentPane().add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 800, 70));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Icon.png"))); // NOI18N
        getContentPane().add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 160, 130));

        lblMessage.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText("Thank You For Using This Application! #Enjoy");
        getContentPane().add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 800, 290));

        btnHelp.setBackground(new java.awt.Color(204, 204, 255));
        btnHelp.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/helpIcon.jpg"))); // NOI18N
        btnHelp.setText("Don't know how to solve Sudoku? Click Me");
        btnHelp.setToolTipText("This Will Play Videos On How To Solve Sudoku");
        btnHelp.setBorderPainted(false);
        btnHelp.setFocusPainted(false);
        btnHelp.setOpaque(false);
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        getContentPane().add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 550, 50));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Background1.jpg"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
     
        String tutorialURI = "";
        tutorialURI = "https://www.google.com/";
        Desktop thisDesktop = Desktop.getDesktop();
        try {
            try {
                thisDesktop.browse(new URI(tutorialURI));
            } catch (URISyntaxException uriEx) {
                System.out.println("URI Syntax Error: " + uriEx.getMessage());
            }
        } catch (IOException ioEx) {
            System.out.println("IO Exception: " + ioEx.getMessage());
        }

    }//GEN-LAST:event_btnHelpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHelp;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    // End of variables declaration//GEN-END:variables
}//Welcome Class
